# Setup
title: Fulcrum Developers
name: Fulcrum Developers
url: http://developer.fulcrumapp.com
relative_permalinks: false
port: 4010
gems:
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed

feed:
  path: atom.xml

# Dependencies
markdown: kramdown
kramdown:
  input: GFM
highlighter: pygments

# Permalinks
permalink: /:categories/:title/


collections:
  api:
    output: true
    permalink: /api/:path/
  endpoints:
    output: true
    permalink: /endpoints/:path/
  general:
    output: true
    permalink: /general/:path/
  expressions:
    output: true
    permalink: /expressions/:path/
  expression-examples:
    output: true
    permalink: /expressions/examples/:path/
  data-events:
    output: true
    permalink: /data-events/:path/

#files to exclude, array
exclude:
  - CONTRIBUTING.md
  - README.md
  - bundle
  - script
  - CNAME
  - Gemfile
  - Gemfile.lock
  - ".bundle"
  - vendor
